/* eslint-disable indent */
export const all_routes = {
  dashboard: "/admin-dashboard",
  institution:'/institution-registration',
  addinstitution:'/addinstitution',
  reports : "/reports",
  latestnews:"/latest-news",
  createlatestnews:"/create-news",
  editnews:"/edit-news",
  studentslist:"/students",
  mentorslist:"/mentors",
  teamslist:"/teams",
  adminlist:"/admins",
  mentortableview:"/mentor-view",
  popup:"/popup",
  InstOption:"/instOption",
  EmailList:"/emailList",
  createemail:"/create-email",
  resendemail:"/resend-email",
  searchCid:"/search-cid",
  mentordetails:"/mentor-details",
  studentreport:"Student-Report",
  mentorEdit:"/admin-mentor-edit",
  studenttableview:"/student-view",
  insttableview:"/Institution-view",

  stuedit:"/student-edit",
  instedit:"/Institution-edit",

  instruction:"/instruction",
  adminsupport:"/admin-support",
  studentsupport: "/student-support",
institutionview:"/view-profile",
inststuedit:"/Institution-student-edit",
institutionUsersList:"/institution-users-list",
instprogress:"/institution-progress",
adminIdeareport:"/idea-submission-report",
adminaddinstitution:"/add-institution",
  adminresponse:"/admin/support-journey/ans-ticket",
  createpopup:"/create-popup",
  reportsregistration : "/reportsregistration",
  reportsteacher : "/reportsteacher",
  adminresources : "/adminresources",
  createResource : "/createResource",
  editResource : "/editResource",
  editinstitution:"/edit-institution",
  mentordashboard: "/institution-dashboard",
  teamdashboard: "/team-dashboard",
  teamProfile: "/team-profile",
  studentProfile: "/student-profile",
  studentProfileEdit: "/studentProfileEdit",
  studentCP: "/student-changePassword",
  studentdashboard: "/student-dashboard",
  studentTeam: "/student-team",
  studentTeamView: "/student-teamView",
  studentTeamEdit: "/student-teamEdit",
  studentTeamAdd: "/student-teamAdd",
  studentCertificate: "/certificate",
  studentpostsurvey: "/studentpostsurvey",
  studentpresurvey: "/studentpresurvey",
  CreatepilotStudent: "/CreatepilotStudent",
  addstudent : "/addstudent",
  AddCrew1Stu: "/AddCrew1Stu",
  AddCrew2Stu: "/AddCrew2Stu",
  AddCrew3Stu: "/AddCrew3Stu",
  studentedit: "/studentedit",
  tecresource: "/tecresource",
  studentresource: "/studentresource",
  mentorpresurvey: "/mentorpresurvey",
  mentorpostsurvey: "/mentorpostsurvey",
  mentorcourse: "/mentorcourse/:id",
  studentcourse: "/studentcourse/:id",
  studentcourseMenu: "/studentcourseMenu",
  mentorsupport: "/mentorsupport",
  mentorcertificate: "/mentorcertificate",
  mentorchangepwd: "/mentorchangepwd",
  mentorteams: "/mentorteams",
  idea: "/idea",
  statedashboard: "/state-dashboard",
  eadmindashboard: "/eadmin/dashboard",
  eadminevaluation:"/eadmin/evaluationStatus",
eadminstats:"/eadmin/evaluationStatus/viewlist",
editeval:"/edit-evaluator",
mentorprofile:"/mentorprofile",
eadminEvaluationProcess:"/eadmin/evaluationProcess",
eadminevaluator:"/eadmin/evaluator",
eadminfinal:"/eadmin/evaluationStatus/viewfinallist",
eadminRest:"/eadmin-changepwd",
eadminDist:'/eadmin/selectingDistricts-evaluationProcess',
evalState:"/evaluator/selecting-states",
evalinstructions:"/evaluator/instructions",
evalsubmit:"/evaluator/submitted-ideas",
evalsubmitwo:"/evaluator2/submitted-ideas",
evalchange:"/evaluator/change-password",
evlL1:"/evaluator/evaluated-ideas",
evlL2:"/evaluator/evaluated-ideasL2",
evlProfile:"/evaluator-profile",
evalReports:"/reports-card",
evalL1:"/l1-report",
evalL2:"/l2-report",
evalL3:"/l3-report",
  adminpassword: "/admin-password",

 
};
