/* eslint-disable no-irregular-whitespace */
/* eslint-disable indent */
export const stateList = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Telangana",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
export const districtList = {
  "Andaman and Nicobar Islands": [
    "Nicobar",
    "North and Middle Andaman",
    "South Andaman",
  ],
  "Andhra Pradesh": [
    "Amalapuram",
    "Anantapur",
    "Bhimavaram",
    "Chittoor",
    "East Godavari",
    "Eluru",
    "Guntur",
    "Hindupur",
    "Kakinada",
    "Krishna",
    "Kurnool",
    "Machilipatnam",
    "Madanapalle",
    "Markapur",
    "Nandyal",
    "Narasaraopet",
    "Nellore",
    "Ongole",
    "Prakasam",
    "Rajahmundry",
    "Satyavedu",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "YSR Kadapa",
  ],
  "Arunachal Pradesh": [
    "Anjaw",
    "Changlang",
    "Dibang Valley",
    "East Kameng",
    "East Siang",
    "Kra Daadi",
    "Kurung Kumey",
    "Lepa Rada",
    "Lohit",
    "Longding",
    "Lower Dibang Valley",
    "Lower Siang",
    "Lower Subansiri",
    "Namsai",
    "Pakke Kessang",
    "Papum Pare",
    "Shi Yomi",
    "Siang",
    "Tawang",
    "Tirap",
    "Upper Dibang Valley",
    "Upper Siang",
    "Upper Subansiri",
    "West Kameng",
    "West Siang",
  ],
  Assam: [
    "Bajali",
    "Baksa",
    "Barpeta",
    "Biswanath",
    "Bongaigaon",
    "Cachar",
    "Charaideo",
    "Chirang",
    "Darrang",
    "Dhemaji",
    "Dhubri",
    "Dibrugarh",
    "Dima Hasao",
    "Goalpara",
    "Golaghat",
    "Hailakandi",
    "Hojai",
    "Jorhat",
    "Kamrup",
    "Kamrup Metropolitan",
    "Karbi Anglong",
    "Karimganj",
    "Kokrajhar",
    "Lakhimpur",
    "Majuli",
    "Morigaon",
    "Nagaon",
    "Nalbari",
    "Sivasagar",
    "Sonitpur",
    "South Salmara-Mankachar",
    "Tamulpur",
    "Tinsukia",
    "Udalguri",
    "West Karbi Anglong",
  ],
  Bihar: [
    "Araria",
    "Arwal",
    "Aurangabad",
    "Banka",
    "Begusarai",
    "Bhagalpur",
    "Bhojpur",
    "Buxar",
    "Darbhanga",
    "East Champaran (Motihari)",
    "Gaya",
    "Gopalganj",
    "Jamui",
    "Jehanabad",
    "Kaimur (Bhabua)",
    "Katihar",
    "Khagaria",
    "Kishanganj",
    "Lakhisarai",
    "Madhepura",
    "Madhubani",
    "Munger (Monghyr)",
    "Muzaffarpur",
    "Nalanda",
    "Nawada",
    "Patna",
    "Purnia (Purnea)",
    "Rohtas",
    "Saharsa",
    "Samastipur",
    "Saran",
    "Sheikhpura",
    "Sheohar",
    "Sitamarhi",
    "Siwan",
    "Supaul",
    "Vaishali",
    "West Champaran",
  ],
  Chandigarh: ["Chandigarh"],
  Chhattisgarh: [
    "Balarampur Ramanujganj",
    "Balod",
    "Baloda Bazar",
    "Balrampur",
    "Bastar",
    "Bemetara",
    "Bemetara",
    "Bijapur",
    "Bilaspur",
    "Dantewada (South Bastar)",
    "Dhamtari",
    "Durg",
    "Gariyaband",
    "Gaurela-Pendra-Marwahi",
    "Janjgir-Champa",
    "Jashpur",
    "Kabirdham (Kawardha)",
    "Kanker (North Bastar)",
    "Khairagarh-Chhuikhadan-Gandai",
    "Kondagaon",
    "Kondagaon",
    "Korba",
    "Koriya (Korea)",
    "Mahasamund",
    "Mungeli",
    "Narayanpur",
    "Raigarh",
    "Raipur",
    "Rajnandgaon",
    "Sarangarh-Bilaigarh",
    "Sukma",
    "Surajpur",
    "Surguja",
  ],
  "Dadra and Nagar Haveli and Daman and Diu": [
    "Dadra and Nagar Haveli",
    "Daman",
    "Diu",
  ],
  Delhi: [
    "Central Delhi",
    "East Delhi",
    "New Delhi",
    "North Delhi",
    "North East Delhi",
    "North West Delhi",
    "Shahdara",
    "South Delhi",
    "South East Delhi",
    "South West Delhi",
    "West Delhi",
  ],
  Goa: ["North Goa", "South Goa"],
  Gujarat: [
    "Ahmedabad",
    "Amreli",
    "Anand",
    "Aravalli",
    "Banaskantha (Palanpur)",
    "Bharuch",
    "Bhavnagar",
    "Botad",
    "Chhota Udaipur",
    "Dahod",
    "Dang (Ahwa)",
    "Devbhoomi Dwarka",
    "Gandhinagar",
    "Gir Somnath",
    "Jamnagar",
    "Junagadh",
    "Kheda (Nadiad)",
    "Kutch",
    "Mahisagar",
    "Mehsana",
    "Morbi",
    "Narmada (Rajpipla)",
    "Navsari",
    "Panchmahal (Godhra)",
    "Patan",
    "Porbandar",
    "Rajkot",
    "Sabarkantha (Himmatnagar)",
    "Surat",
    "Surendranagar",
    "Tapi (Vyara)",
    "Vadodara",
    "Valsad",
  ],
  Haryana: [
    "Ambala",
    "Bhiwani",
    "Charkhi Dadri",
    "Faridabad",
    "Fatehabad",
    "Gurugram (Gurgaon)",
    "Hisar",
    "Jhajjar",
    "Jind",
    "Kaithal",
    "Karnal",
    "Kurukshetra",
    "Mahendragarh",
    "Nuh",
    "Palwal",
    "Panchkula",
    "Panipat",
    "Rewari",
    "Rohtak",
    "Sirsa",
    "Sonipat",
    "Yamunanagar",
  ],
  "Himachal Pradesh": [
    "Bilaspur",
    "Chamba",
    "Hamirpur",
    "Kangra",
    "Kinnaur",
    "Kullu",
    "Lahaul & Spiti",
    "Mandi",
    "Shimla",
    "Sirmaur (Sirmour)",
    "Solan",
    "Una",
  ],
  "Jammu and Kashmir": [
    "Anantnag",
    "Bandipora",
    "Baramulla",
    "Budgam",
    "Doda",
    "Ganderbal",
    "Jammu",
    "Kathua",
    "Kishtwar",
    "Kulgam",
    "Kupwara",
    "Poonch",
    "Pulwama",
    "Rajouri",
    "Ramban",
    "Reasi",
    "Samba",
    "Shopian",
    "Srinagar",
    "Udhampur",
  ],
  Jharkhand: [
    "Bokaro",
    "Chatra",
    "Deoghar",
    "Dhanbad",
    "Dumka",
    "East Singhbhum",
    "Garhwa",
    "Giridih",
    "Godda",
    "Gumla",
    "Hazaribagh",
    "Jamtara",
    "Khunti",
    "Koderma",
    "Latehar",
    "Lohardaga",
    "Pakur",
    "Palamu",
    "Ramgarh",
    "Ranchi",
    "Sahibganj",
    "Seraikela-Kharsawan",
    "Simdega",
    "West Singhbhum",
  ],
  Karnataka: [
    "Bagalkot",
    "Ballari (Bellary)",
    "Belagavi (Belgaum)",
    "Bengaluru (Bangalore) Rural",
    "Bengaluru (Bangalore) Urban",
    "Bidar",
    "Chamarajanagar",
    "Chikkaballapur",
    "Chikkamagaluru (Chikmagalur)",
    "Chitradurga",
    "Dakshina Kannada",
    "Davanagere",
    "Dharwad",
    "Gadag",
    "Hassan",
    "Haveri",
    "Kalaburagi (Gulbarga)",
    "Kodagu",
    "Kolar",
    "Koppal",
    "Mandya",
    "Mysuru (Mysore)",
    "Raichur",
    "Ramanagara",
    "Shivamogga (Shimoga)",
    "Tumakuru (Tumkur)",
    "Udupi",
    "Uttara Kannada (Karwar)",
    "Vijayanagara",
    "Vijayapura (Bijapur)",
    "Yadgir",
  ],
  Kerala: [
    "Alappuzha",
    "Ernakulam",
    "Idukki",
    "Kannur",
    "Kasaragod",
    "Kollam",
    "Kottayam",
    "Kozhikode",
    "Malappuram",
    "Palakkad",
    "Pathanamthitta",
    "Thiruvananthapuram",
    "Thrissur",
    "Wayanad",
  ],
  Ladakh: ["Kargil", "Leh"],
  Lakshadweep: ["Lakshadweep"],
  "Madhya Pradesh": [
    "Agar Malwa",
    "Alirajpur",
    "Anuppur",
    "Ashoknagar",
    "Balaghat",
    "Barwani",
    "Betul",
    "Bhind",
    "Bhopal",
    "Burhanpur",
    "Burhanpur",
    "Chhatarpur",
    "Chhindwara",
    "Damoh",
    "Datia",
    "Dewas",
    "Dhar",
    "Dindori",
    "Guna",
    "Gwalior",
    "Harda",
    "Hoshangabad",
    "Hoshangabad (recently renamed as Narmadapuram)",
    "Indore",
    "Jabalpur",
    "Jhabua",
    "Katni",
    "Khandwa",
    "Khargone",
    "Mandla",
    "Mandsaur",
    "Mhow (Dr. Ambedkar Nagar)",
    "Morena",
    "Narsinghpur",
    "Neemuch",
    "Niwari",
    "Panna",
    "Raisen",
    "Rajgarh",
    "Ratlam",
    "Rewa",
    "Sagar",
    "Satna",
    "Sehore",
    "Seoni",
    "Shahdol",
    "Shajapur",
    "Sheopur",
    "Shivpuri",
    "Sidhi",
    "Singrauli",
    "Tikamgarh",
    "Ujjain",
    "Umaria",
    "Vidisha",
  ],
  Maharashtra: [
    "Ahmednagar",
    "Akola",
    "Amravati",
    "Aurangabad",
    "Beed",
    "Bhandara",
    "Buldhana",
    "Chandrapur",
    "Dhule",
    "Gadchiroli",
    "Gondia",
    "Hingoli",
    "Jalgaon",
    "Jalna",
    "Kolhapur",
    "Latur",
    "Mumbai City",
    "Mumbai Suburban",
    "Nagpur",
    "Nanded",
    "Nandurbar",
    "Nashik",
    "Osmanabad",
    "Palghar",
    "Parbhani",
    "Pune",
    "Raigad",
    "Ratnagiri",
    "Sangli",
    "Satara",
    "Sindhudurg",
    "Solapur",
    "Thane",
    "Wardha",
    "Washim",
    "Yavatmal",
  ],
  Manipur: [
    "Bishnupur",
    "Chandel",
    "Churachandpur",
    "Imphal East",
    "Imphal West",
    "Jiribam",
    "Kakching",
    "Kamjong",
    "Kangpokpi",
    "Noney",
    "Pherzawl",
    "Senapati",
    "Tamenglong",
    "Tengnoupal",
    "Thoubal",
    "Ukhrul",
  ],
  Meghalaya: [
    "East Garo Hills",
    "East Jaintia Hills",
    "East Khasi Hills",
    "Eastern West Khasi Hills",
    "North Garo Hills",
    "Ri Bhoi",
    "South Garo Hills",
    "South West Garo Hills",
    "South West Khasi Hills",
    "West Garo Hills",
    "West Jaintia Hills",
    "West Khasi Hills",
  ],
  Mizoram: [
    "Aizawl",
    "Champhai",
    "Hnahthial",
    "Khawzawl",
    "Kolasib",
    "Lawngtlai",
    "Lunglei",
    "Mamit",
    "Saiha",
    "Saitual",
    "Serchhip",
  ],
  Nagaland: [
    "Chümoukedima",
    "Dimapur",
    "Kiphire",
    "Kohima",
    "Longleng",
    "Mokokchung",
    "Mon",
    "Niuland",
    "Noklak",
    "Peren",
    "Phek",
    "Shamator",
    "Tseminyu",
    "Tuensang",
    "Wokha",
    "Zünheboto",
  ],
  Odisha: [
    "Angul",
    "Balangir",
    "Balasore (Baleswar)",
    "Bargarh (Baragarh)",
    "Bhadrak",
    "Boudh (Baudh)",
    "Cuttack",
    "Deogarh (Debagarh)",
    "Dhenkanal",
    "Gajapati",
    "Ganjam",
    "Jagatsinghpur",
    "Jajpur",
    "Jharsuguda",
    "Kalahandi",
    "Kandhamal",
    "Kendrapara",
    "Kendujhar (Keonjhar)",
    "Khordha",
    "Koraput",
    "Malkangiri",
    "Mayurbhanj",
    "Nabarangpur",
    "Nayagarh",
    "Nuapada",
    "Puri",
    "Rayagada",
    "Sambalpur",
    "Sonepur (Subarnapur)",
    "Sundargarh",
  ],
  Puducherry: ["Karaikal", "Mahe", "Puducherry", "Yanam"],
  Punjab: [
    "Amritsar",
    "Barnala",
    "Bathinda",
    "Faridkot",
    "Fatehgarh Sahib",
    "Fazilka",
    "Ferozepur",
    "Gurdaspur",
    "Hoshiarpur",
    "Jalandhar",
    "Kapurthala",
    "Ludhiana",
    "Malerkotla",
    "Mansa",
    "Moga",
    "Pathankot",
    "Patiala",
    "Rupnagar",
    "Sahibzada Ajit Singh Nagar (Mohali)",
    "Sangrur",
    "Shaheed Bhagat Singh Nagar (Nawanshahr)",
    "Sri Muktsar Sahib",
    "Tarn Taran",
  ],
  Rajasthan: [
    "Ajmer",
    "Alwar",
    "Banswara",
    "Baran",
    "Barmer",
    "Bharatpur",
    "Bhilwara",
    "Bikaner",
    "Bundi",
    "Chittorgarh",
    "Churu",
    "Dausa",
    "Dholpur",
    "Dungarpur",
    "Hanumangarh",
    "Jaipur",
    "Jaisalmer",
    "Jalore",
    "Jhalawar",
    "Jhunjhunu",
    "Jodhpur",
    "Karauli",
    "Kota",
    "Nagaur",
    "Pali",
    "Pratapgarh",
    "Rajsamand",
    "Sawai Madhopur",
    "Sikar",
    "Sirohi",
    "Sri Ganganagar",
    "Tonk",
    "Udaipur",
  ],
  Sikkim: [
    "Gangtok (East Sikkim)",
    "Gyalshing (West Sikkim)",
    "Mangan (North Sikkim)",
    "Namchi (South Sikkim)",
    "Pakyong",
    "Soreng",
  ],
  Telangana: [
    "Adilabad",
    "Bhadradri Kothagudem",
    "Hyderabad",
    "Jagtial",
    "Jangaon",
    "Jayashankar Bhupalpally",
    "Jogulamba Gadwal",
    "Kamareddy",
    "Karimnagar",
    "Khammam",
    "Komaram Bheem Asifabad",
    "Mahabubabad",
    "Mahabubnagar",
    "Mancherial",
    "Medak",
    "Medchal-Malkajgiri",
    "Mulugu",
    "Nagarkurnool",
    "Nalgonda",
    "Narayanpet",
    "Nirmal",
    "Nizamabad",
    "Peddapalli",
    "Rajanna Sircilla",
    "Rangareddy",
    "Sangareddy",
    "Siddipet",
    "Suryapet",
    "Vikarabad",
    "Wanaparthy",
    "Warangal (Rural)",
    "Warangal (Urban)",
    "Yadadri Bhuvanagiri",
  ],
  "Tamil Nadu": [
    "ARIYALUR",
    "CHENGALPATTU",
    "CHENNAI",
    "COIMBATORE",
    "CUDDALORE",
    "DHARMAPURI",
    "DINDIGUL",
    "ERODE",
    "KALLAKURICHI",
    "KANCHEEPURAM",
    "KANNIYAKUMARI",
    "KARUR",
    "KRISHNAGIRI",
    "MADURAI",
    "MAYILADUTHURAI",
    "NAGAPATTINAM",
    "NAMAKKAL",
    "NILGIRIS",
    "PERAMBALUR",
    "PUDUKKOTTAI",
    "RAMANATHAPURAM",
    "RANIPET",
    "SALEM",
    "SIVAGANGAI",
    "TENKASI",
    "THANJAVUR",
    "THENI",
    "THOOTHUKKUDI",
    "TIRUCHIRAPPALLI",
    "TIRUNELVELI",
    "TIRUPATTUR",
    "TIRUPPUR",
    "TIRUVALLUR",
    "TIRUVANNAMALAI",
    "TIRUVARUR",
    "VELLORE",
    "VILLUPURAM",
    "VIRUDHUNAGAR",
  ],
  Tripura: [
    "Dhalai",
    "Gomati",
    "Khowai",
    "North Tripura",
    "Sepahijala",
    "South Tripura",
    "Unakoti",
    "West Tripura",
  ],
  "Uttar Pradesh": [
    "Agra",
    "Aligarh",
    "Ambedkar Nagar",
    "Amethi (Chatrapati Sahuji Mahraj Nagar)",
    "Amroha (J.P. Nagar)",
    "Auraiya",
    "Ayodhya (Faizabad)",
    "Azamgarh",
    "Baghpat",
    "Bahraich",
    "Ballia",
    "Balrampur",
    "Banda",
    "Barabanki",
    "Bareilly",
    "Basti",
    "Bhadohi",
    "Bijnor",
    "Budaun",
    "Bulandshahr",
    "Chandauli",
    "Chitrakoot",
    "Chitrakoot",
    "Deoria",
    "Etah",
    "Etawah",
    "Farrukhabad",
    "Fatehpur",
    "Firozabad",
    "Gautam Buddha Nagar",
    "Ghaziabad",
    "Ghazipur",
    "Gonda",
    "Gorakhpur",
    "Hamirpur",
    "Hapur (Panchsheel Nagar)",
    "Hardoi",
    "Hathras",
    "Jalaun",
    "Jaunpur",
    "Jhansi",
    "Kannauj",
    "Kanpur Dehat",
    "Kanpur Nagar",
    "Kasganj (Kanshiram Nagar)",
    "Kaushambi",
    "Kheri",
    "Kushinagar (Padrauna)",
    "Lalitpur",
    "Lucknow",
    "Mahoba",
    "Mainpuri",
    "Mathura",
    "Mau",
    "Meerut",
    "Mirzapur",
    "Moradabad",
    "Muzaffarnagar",
    "Pilibhit",
    "Pratapgarh",
    "Prayagraj (Allahabad)",
    "Rae Bareli",
    "Rampur",
    "Saharanpur",
    "Sambhal (Bhim Nagar)",
    "Sant Kabir Nagar",
    "Shahjahanpur",
    "Shamli (Prabuddh Nagar)",
    "Shravasti",
    "Siddharthnagar",
    "Sitapur",
    "Sonbhadra",
    "Sultanpur",
    "Unnao",
    "Varanasi",
  ],
  Uttarakhand: [
    "Almora",
    "Bageshwar",
    "Chamoli",
    "Champawat",
    "Dehradun",
    "Haridwar",
    "Nainital",
    "Pauri Garhwal",
    "Pithoragarh",
    "Rudraprayag",
    "Tehri Garhwal",
    "Udham Singh Nagar",
    "Uttarkashi",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Cooch Behar",
    "Dakshin Dinajpur (South Dinajpur)",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Bardhaman (West Bardhaman)",
    "Paschim Medinipur (West Medinipur)",
    "Purba Bardhaman (East Bardhaman)",
    "Purba Medinipur (East Medinipur)",
    "Purulia",
    "South 24 Parganas",
    "Uttar Dinajpur (North Dinajpur)",
  ],
};
export const userList = [
  "Institution",
  "Student"
];
export const navList = {
  Mentor: [
    "/institution-dashboard",
    "/mentorcourse/1",
    "/mentorteams",
    "/tecresource",
    "/mentorpostsurvey",
    "/mentorsupport",
    "/mentorprofile",
    "/mentorchangepwd",
  ],
  Student: [
    "/student-dashboard",
    "/studentcourse/1",
    "/idea",
    "/studentpostsurvey",
    "/certificate",
    "/studentresource",
    "/student-profile"],
};
export const collegeType = [
  "Govt Junior College",
  "Govt ITI College",
  "Govt Polytechnic College",
  "Govt Degree College",
  "Social Welfare College",
  "Tribal Welfare College",
  "Private College",
  "Other"
];
export const collegeNameList = {
  "Govt Junior College": [
    "Other"
  ],
  "Govt ITI College": [
    "Govt ITI Adilabad",
    "Govt ITI Mancherial",
    "Govt ITI Mandamarri",
    "Govt ITI Srirampur",
    "Govt ITI Jannaram",
    "Govt ITI Utnoor",
    "Govt ITI Peddapalli",
    "Govt ITI Karimnagar",
    "Govt ITI Ramagundam",
    "Govt ITI Kataram",
    "Govt ITI Jagtial",
    "Govt ITI Siricilla",
    "Govt ITI (B) Warangal",
    "Govt ITI Hanamkonda",
    "Govt RITI(T) Eturunagaram",
    "Govt ITI Bhupalapally",
    "Govt ITI Mahabubabad",
    "Govt ITI Kothagudem",
    "Govt ITI Khammam",
    "Govt RITI Bhadrachalam",
    "Govt RITI Wazeedu",
    "Govt ITI Manuguru",
    "Govt. ITI Mallepally",
    "Govt. ITI Musheerabad",
    "Govt. ITI Old City",
    "Govt. ITI Sanath nagar",
    "Govt. ITI Vijayanagar colony",
    "Govt. DLTC or ITI Shanthinagar",
    "Govt. ITI(G) Santhoshagar",
    "Govt. ITI Khairathabad",
    "Govt.ITI Sangareddy",
    "Govt. ITI Patanacheru",
    "Govt. ITI Hatnoora",
    "Govt.ITI Medak",
    "Govt.ITI Siddipet",
    "Govt. ITI Dubbak",
    "Govt.ITI Kuknoorpally",
    "Govt.ITI Shadnagar",
    "Govt.ITI Medchal",
    "Govt.ITI Alwal",
    "Govt.ITI Shameerpet",
    "Govt.DLTC or ITI Vikarabad",
    "Govt.DLTC or ITI Mahabubnagar",
    "Govt. RITI(G) Mahabubnagar",
    "Govt.ITI Wanaparthy",
    "Govt. RITI Mannanur",
    "Govt.ITI Gadwal",
    "Govt.ITI(B) Nalgonda",
    "Govt.ITI(G) Nalgonda",
    "Govt.ITI Dindi",
    "Govt.ITI Anumula",
    "Govt.ITI Bhongir",
    "Govt.ITI Aler",
    "Govt.ITI(B) Nizamabad",
    "Govt.ITI(G) Nizamabad",
    "Govt.ITI(M) Bodhan",
    "Govt.ITI Kammarpally",
     "Other"
  ],
  "Govt Polytechnic College": [
    "Government Polytechnic, MasabTank",
    "J.N. Government Polytechnic, Ramanthapur",
    "Government Polytechnic, Warangal",
    "Government Polytechnic, Nizamabad",
    "Government Polytechnic, Mahabubnagar",
    "KDR Government Polytechnic, Wanaparthy",
    "SS Government Polytechnic, Zaheerabad",
    "SRRS Government Polytechnic, Sircilla",
    "Smt. Durgabai Deshmukh Womens' Technical Training Institute, Secunderabad",
    "SG Government Polytechnic, Adilabad",
    "Government Polytechnic, Nalgonda",
    "Government Polytechnic for Women, Warangal",
    "Government Polytechnic, Kothagudem",
    "SGM Government Polytechnic, Abdullapurmet",
    "Government Institute of Leather Technology, Hyderabad",
    "Government Institute of Electronics, Secunderabad",
    "Q.Q. Government PoIytechnic, OId city, Hyderabad",
    "Government Polytechnic for Women, Nizmabad",
    "Government Polytechnic for Women, Medak",
    "GMR. Polytechnic, Gajwel",
    "Government Polytechnic for Women, Suryapet",
    "Government Polytechnic, Bellampally",
    "Dr.B.R. Ambedkar Government Model Residencial Polytechnic for Women (SC), Karimnagar",
    "Government Polytechnic For Women (Minorities), Badangpet",
    "Government Polytechnic, Kataram",
    "Government Polytechnic, Station Ghanpur",
    "Government Polytechnic, Vikarabad",
    "Government Polytechnic, Nirmal",
    "Government Polytechnic, Tirumalagiri",
    "Government Polytechnic, Madhira",
    "Government Polytechnic, Yadagirigutta",
    "Government Polytechnic, Gomaram (NARSAPUR)",
    "Government Polytechnic, Korutla",
    "Government Polytechnic, Siddipet",
    "Government Polytechnic, Kotagiri",
    "Government Polytechnic, Nandipet",
    "Government Polytechnic, Parkal",
    "Government Polytechnic, Sangareddy",
    "Government Polytechnic, Narayankhed",
    "Government Polytechnic, Gadwal",
    "Government Polytechnic, Jogipet",
    "Government Polytechnic, Medchal",
    "Government Polytechnic, Chegunta",
    "Government Polytechnic for Women, Siddipet",
    "Government Polytechnic for Women, Jogipet",
    "Government Polytechnic, Vaddepally",
    "Government Polytechnic for Women, Pebbair",
    "Government Polytechnic, Kosgi",
    "Government Polytechnic, Navipet",
    "G M R Polytechnic, Utnoor",
    "Government Polytechnic, Nagarjuna Sagar",
    "Government Polytechnic, Cherial",
    "Government Polytechnic, Husnabad",
    "Government Polytechnic for Women, Secunderabad",
     "Other"
  ],
  "Govt Degree College": [
    "GDC Chanchalguda",
    "GDC Falaknuma",
    "GDC Khairatabad",
    "GDC Narayanaguda",
    "GDC Sitaphalmandi",
    "GDC Vidyanagar",
    "GDCA Nayapul",
    "GDCW Golconda",
    "GDCW Hussainialam",
    "GDCW Nampally",
    "GDCWA Begumpet",
    "GDC A&C Adilabad",
    "GDC Utnoor",
    "GDCS Adilabad",
    "GDC Bhadrachalam",
    "GDC Kothagudem",
    "GDC Manuguru",
    "GDC Paloncha",
    "GDC Yellandu",
    "GDC Jagtial",
    "GDC Koratla",
    "GDC Metpally",
    "GDCW Jagtial",
    "GDC Jangaon",
    "GDC Bhupalpally",
    "GDC Mahadevpur",
    "GDC Huzurabad",
    "GDC Jammikunta",
    "GDC Karimnagar",
    "GDCW Karimnagar",
    "GDC Madhira",
    "GDC Nelakondapalli",
    "GDC Sathupally",
    "GDCA Khammam",
    "GDCW Khammam",
    "GDC Kagajnagar",
    "GDC Garla",
    "GDC Mahabubabad",
    "GDC Maripeda",
    "GDC Thorrur",
    "GDC Bellampally",
    "GDC Chennoor",
    "GDC Luxettipet",
    "GDC Mancherial",
    "GDC Eturunagaram",
    "GDC Mulugu",
    "GDC Bhainsa",
    "GDC Nirmal",
    "GDC Godavarikhani",
    "GDC Manthani",
    "GDC Peddapalli",
    "GDC Agraharam",
    "GDC Gambhiraopet",
    "GDC Narsampet",
    "GDC Parkal",
    "GDC Wardhannapet",
    "GDC Hanamkonda",
    "GDC Rangasaipet",
    "GDCW Warangal",
    "GDC Gadwal",
    "GDC Shantinagar",
    "GDCW Gadwal",
    "GDC Banswada",
    "GDC Bichkunda",
    "GDC Kamareddy",
    "GDC Yellareddy",
    "GDC Jadcherla",
    "GDCA Mahabubanagar",
    "GDCW Mahabubnagar",
    "GDC Medak",
    "GDC Narsapur",
    "GDC Kukatpally",
    "GDC Malkajgiri",
    "GDC Amrabad",
    "GDC Kalwakurthy",
    "GDC Kollapur",
    "GDC Kondanagula",
    "GDC Palem",
    "GDCA&C Nagarkurnool",
    "GDCS Nagarkurnool",
    "GDC Chandur",
    "GDC Devarakonda",
    "GDC Haliya",
    "GDC Miryalguda",
    "GDC Nakrekal",
    "GDCA Nalgonda",
    "GDCW Nalgonda",
    "GDC Narayanpet",
    "GDC Armoor",
    "GDC Bheemgal",
    "GDC Bodhan",
    "GDC Dharpally",
    "GDC Morthad",
    "GDC Shakarnagar",
    "GDCA Nizamabad",
    "GDC Chevella",
    "GDC Hayathnagar",
    "GDC Ibrahimpatnam",
    "GDC Maheshwaram (Badangpet)",
    "GDC Serilingampally",
    "GDC Shadnagar",
    "GDC Uppal",
    "GDC Jogipet",
    "GDC Narayankhed",
    "GDC Patancheru",
    "GDC Sadasivpet",
    "GDC Zaheerabad",
    "GDCA Sangareddy",
    "GDCW Sangareddy",
    "GDC Cherial",
    "GDC Dubbak",
    "GDC Husnabad",
    "GDCA Siddipet",
    "GDCM Gajwel",
    "GDCW Gajwel",
    "GDCW Siddipet",
    "GDC Huzurnagar",
    "GDC Kodad",
    "GDC Kodangal",
    "GDC Pargi",
    "GDC Tandur",
    "GDC Vikarabad",
    "GDC Atmakur",
    "GDC Pebbair",
    "GDC Wanaparthy",
    "GDCW Wanaparthy",
    "GDC Alair",
    "GDC Ramannapet",
     "Other"
  ],
  "Social Welfare College": [
    "TSWRDCW, Adilabad",
    "TSWRDCW, Mancherial",
    "TSWRDCW, Nirmal",
    "TSWRDCW, Nizamabad",
    "TSWRDCW, Armoor",
    "TSWRDCW, Jagtial",
    "TSWRDCW, Bhupalapally",
    "TSWRDCW, Kothagudem",
    "TSWRDCW, Mahabubabad",
    "TSWRDCW, Warangal East",
    "TSWRDCW, Warangal West",
    "TSWRDCW, Karimnagar",
    "TSWRDCW, Sircilla",
    "TSWRDCW, Kamareddy",
    "TSWRDCW, Sangareddy",
    "TSWRDCW, Medak",
    "TSWRDCW, Siddipet",
    "TSWRDCW, Bhongir",
    "TSWRDCW, Jagathgirigutta",
    "TSWRDCW, Mahendrahills",
    "TSWRDCW, L.B.Nagar",
    "TSWRDCW, Budvel",
    "TSWRDCW, Ibrahimpatnam",
    "TSWRDCW, Vikarabad",
    "TSWRDCW, Mahabubnagar",
    "TSWRDCW, Wanaparthy",
    "TSWRDCW, Nagarkurnool",
    "TSWRDCW, Nalgonda",
    "TSWRDCW, Suryapet",
    "TSWRDCW, Khammam",
     "Other"
  ],
  "Tribal Welfare College": [
    "TTWRDC - Asifabad",
    "TTWRDC - Mulugu",
    "TTWRDC - Utnoor",
    "TTWRDC - Nizamabad",
    "TTWRDC - Siricilla",
    "TTWRDC - Medak",
    "TTWRDC - Dammapet",
    "TTWRDC - Kothagudem",
    "TTWRDC - Mahabubabad",
    "TTWRDC - Khammam",
    "TTWRDC - Jangaon",
    "TTWRDC - Devarakonda",
    "TTWRDC - Suryapet",
    "TTWRDC - Shadnagar",
    "TTWRDC - Mahabubnagar",
    "TTWRDC - Boath",
    "TTWRDC - Karimnagar",
    "TTWRDC - Kamareddy",
    "TTWRDC - Marripeda",
    "TTWRDC - Manuguru",
    "TTWRDC - Sangareddy",
    "TTWRDC - Nagarkurnool",
     "Other"
  ],
  "Private College": [
    "Other"
  ],
  "Other": [
    "Other"
  ]
};
export const yearofstudyList = [
  "1st Year",
  "2nd Year",
  "3rd Year",
  "4th Year",
  "5th Year"
];