
name: Deployment to AP Server

on:
  push:
    branches: dev-for-ap
jobs:
  
  Build_Development:
    if: github.ref == 'refs/heads/dev-for-ap'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install NPM
        run: sudo npm install -g npm@8.15.1

      - name: Set legacy-peer-deps
        run: sudo npm config set legacy-peer-deps true

      - name: Install dependencies
        run: |
          echo Installing source NPM dependencies...
          sudo npm install --force


      - name: Buid the application
        env:
          CI: false
        run: npm run build:dev
        
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-development
          path: build
          
  Deploy_Development:
    needs: Build_Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-development
          path: build
      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev-for-ap'
        env:
          PRIVATE_KEY: ${{ secrets.IMG_AP_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.IMG_AP_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.IMG_AP_HOSTNAME }}:/tmp/yfsi_ap_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.IMG_AP_HOSTNAME }} '
            sudo rm -rf /var/www/html/YFSI-AP/build &&
            sudo mv /tmp/yfsi_ap_fe_build /var/www/html/YFSI-AP/build &&
            cd /var/www/html/YFSI-AP &&
            sudo git fetch origin &&
            sudo git checkout dev-for-ap &&
            sudo git pull origin dev-for-ap '

            

      
  
