
name: Deployment1

on:
  push:
    branches: [development , testing]
jobs:
  
  Build_Development:
    if: github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install NPM
        run: sudo npm install -g npm@8.15.1

      - name: Set legacy-peer-deps
        run: sudo npm config set legacy-peer-deps true

      - name: Install dependencies
        run: |
          echo Installing source NPM dependencies...
          sudo npm install --force


      - name: Buid the application
        env:
          CI: false
        run: npm run build:dev
        
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-development
          path: build
  Build_Testing:
    if: github.ref == 'refs/heads/testing'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install NPM
        run: sudo npm install -g npm@8.15.1

      - name: Set legacy-peer-deps
        run: sudo npm config set legacy-peer-deps true

      - name: Install dependencies
        run: |
          echo Installing source NPM dependencies...
          sudo npm install --force

      - name: Buid the application
        env:
          CI: false
        run: npm run build:stage
        
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-testing
          path: build
      

  Deploy_Development:
    needs: Build_Development
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-development
          path: build
      - name: Deploy to Development
        if: github.ref == 'refs/heads/development'
        env:
          PRIVATE_KEY: ${{ secrets.IMG_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.IMG_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.IMG_HOSTNAME }}:/tmp/img_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.IMG_HOSTNAME }} '
            sudo rm -rf /var/www/html/img-fe/build &&
            sudo mv /tmp/img_fe_build /var/www/html/img-fe/build &&
            cd /var/www/html/img-fe &&
            sudo git fetch origin &&
            sudo git checkout development &&
            sudo git pull origin development '
  Deploy_Testing:
    needs: Build_Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-testing
          path: build       
      - name: Deploy to Testing
        if: github.ref == 'refs/heads/testing'
        env:
          PRIVATE_KEY: ${{ secrets.ATL2_STG_PRIVATE_KEY }}
          HOSTNAME: ${{ secrets.ATL2_STG_HOSTNAME }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          scp -o StrictHostKeyChecking=no -i private_key -r ./build ubuntu@${{ secrets.ATL2_STG_HOSTNAME }}:/tmp/aim_fe_build
          ssh -o StrictHostKeyChecking=no -i private_key ubuntu@${{ secrets.ATL2_STG_HOSTNAME }} '
            sudo rm -rf /var/www/html/aim_fe/build &&
            sudo mv /tmp/aim_fe_build /var/www/html/aim_fe/build &&
            cd /var/www/html/aim_fe &&
            sudo git fetch origin &&
            sudo git checkout testing &&
            sudo git pull origin testing '

            

      
  
